name: Python CI to Docker Hub
on: push

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: venky9922
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/app.py:latest .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/app.py:latest

